version: '3.8'

services:
  app:
    build: .
    container_name: text_sum_app
    environment:
      - MODEL_TYPE=${MODEL_TYPE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
